FROM ubuntu:latest

RUN apt update && apt install -y curl wget net-tools nano build-essential libpcre3\
    libpcre3-dev zlib1g zlib1g-dev libssl-dev libgd-dev nghttp2-client

RUN wget http://nginx.org/download/nginx-1.15.0.tar.gz -O /mnt/nginx.tar.gz \
    && cd /mnt && tar -xf nginx.tar.gz && cd nginx-1.15.0 \
    && ./configure --sbin-path=/usr/bin/nginx --conf-path=/etc/nginx/nginx.conf\
    --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log \
    --with-pcre --pid-path=/var/run/nginx.pid --with-http_ssl_module --with-http_image_filter_module=dynamic \
    --modules-path=/etc/nginx/modules --with-http_v2_module && make && make install

EXPOSE 80 8080 443

RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log

STOPSIGNAL SIGTERM

CMD ["nginx", "-g", "daemon off;"]

WORKDIR /home
